### ISSUE TITLE
Definire schema dati

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ordinanze-covid#1]
Campi da mantenere:

- [x] pro_com
- [ ] provincia
- [x] data_inizio
- [x] data_fine
- [x] link_ordinanza
- [x] id_ordinanza
- [ ] proroga/cessa (?)
- [x] PDF
- [x] nro_pgg
- [ ] sovrapposizione (?)
- [ ] cessa (?)
- [x] nro_ordinanza
- [x] data_ordinanza
- [ ] area_kmq
- [ ] pop_2020
- [x] note
- [x] zona

**Comment by pigreco** [comment]
Non ho capito ancora bene lo scopo di questo repository, ma se servisse solo per rendere disponibile il file [data.csv](https://github.com/opendatasicilia/ordinanze-covid/blob/main/data.csv) allora è possibile eliminare i campi descritti qui (naturalemente solo in github) 
![image](https://user-images.githubusercontent.com/7631137/148350397-f7778abb-d0fb-4a5b-8b35-479ac189761e.png)

**Comment by dennisangemi** [comment]
> se servisse solo per rendere disponibile il file data.csv 

Ciao Totò, io l'ho pensato proprio per rendere disponibile il file data.csv (o json) in modo tale che sia ben documentato e facile da essere raggiunto da chiunque (senza passare per google sheet, che rimane il "motore").

**Comment by dennisangemi** [comment]
Ho aggiunto lo schema anche in formato `yaml` (tanto per fare contento contento @aborruso <3). Se per voi va bene tutto, io chiuderei questa issue.

**Comment by pigreco** [comment]
@dennisangemi ottimo lavoro
per me puoi chiudere issue
