### ISSUE TITLE
rivedere tutte le ordinanze 2021

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/ordinanze-covid#10]
Il [progetto ](https://docs.google.com/spreadsheets/d/14f2AUf3k3jP60sPkUhzqhSIFlTEuUFCfac9b-1_29jc/edit?usp=sharing)è nato per caso e man mano che le ordinanze uscivano si presentavano casi particolari come quelle delle proroghe o cessazione; nel primo caso un comune in proroga continuava la restrizione secondo le nuove date; nel secondo caso cessava immediatamente (alla data della stessa ordinanza) in data di emissione della nuova ordinanza.
Non è stato semplice gestire questi casi, è probabile che ci siano degli errori vedi issue #9.

![image](https://user-images.githubusercontent.com/7631137/148912354-60242a7a-1186-4d2c-830f-d6ab441a1335.png)

Quindi, se volessimo fare un blog post per tutte le ordinanze del 2021, occorre una revisione totale e magari cogliere l'occasione per migliorare l'intero [gsheet](https://docs.google.com/spreadsheets/d/14f2AUf3k3jP60sPkUhzqhSIFlTEuUFCfac9b-1_29jc/edit?usp=sharing).

PS: chissà forse ci sono altri errori che ancora non sono venuti a galla!!!

pensieri?

**EDIT**: oppure rivediamo solo i casi particolari relativi alle proroghe e cessazione!

**Comment by pigreco** [comment]
Appena posso e alla luce di un anno di ordinanze e di esperienza, rivedrò tutte le ordinanze e cercherò di migliorare il foglio elettronico.

vi aggiorno

**Comment by gbvitrano** [comment]
Per calcolare con precisione i giorni, si potrebbero aggiungere altre due colonne `scadenza programma` o `data fine programmata` e `data fine anticipata`

**Comment by gbvitrano** [comment]
e magari anche una colonna `Ordinanza di revoca`

**Comment by gbvitrano** [comment]
Aggiunto filtro tipologia Ordinanza

![image](https://user-images.githubusercontent.com/20488693/148964179-9d93931b-325a-499b-97d4-c41d6d091533.png)

**Comment by pigreco** [comment]
> Aggiunto filtro tipologia Ordinanza
> 
> ![image](https://user-images.githubusercontent.com/20488693/148964179-9d93931b-325a-499b-97d4-c41d6d091533.png)

perché?
ho scritto che ci pensavo io a rivedere tutto, ora che si fa?

**Comment by pigreco** [comment]
ci sto lavorando e ho trovato alcuni errori e orrori

**Comment by dennisangemi** [comment]
> ci sto lavorando e ho trovato alcuni errori e orrori

Il diff di GH rivelerà tutti gli orrori allora haha ;)))))

**Comment by gbvitrano** [comment]
> > Aggiunto filtro tipologia Ordinanza
> > ![image](https://user-images.githubusercontent.com/20488693/148964179-9d93931b-325a-499b-97d4-c41d6d091533.png)
> 
> perché? ho scritto che ci pensavo io a rivedere tutto, ora che si fa?

@pigreco ho lavorato direttamente su tableau, non ho modificato lo sheet di google, i campi nuovi li aggiungo tramite le funzioni di tableau, utilizzando solo i dati delle ordinanze scaricate dal repo.  Quando ci sarà il dataset definitivo, se necessario rifaccio una nuova dashboard utilizzando il nuovo dataset :-) :-) :-)  Per mè un passatempo formativo :-) :-) :-)
La mappa e le tabelle generate con Datawrapper sono alimentate direttamente dallo sheet quindi non influenzati dai dati di tableau.  Non posso far danni li  :-) :-) :-)

**Comment by pigreco** [comment]
@gbvitrano capisco il passatempo, ma comunicandolo avevo frainteso.

**Comment by dennisangemi** [comment]
> passatempo formativo

@gbvitrano questa è la mia nuova espressione preferita ;)

**Comment by pigreco** [comment]
qui nuovo sheet, dove ho rivisto tutte le ordinanze e fatto le dovute correzioni.

![image](https://user-images.githubusercontent.com/7631137/149509853-3fc28d13-fe9b-477c-beed-ffd1c06ab7f3.png)

allora, la vera novità dello sheet sta nel calcolo dei giorni effettivi di restrizione, perché le ordinanze possono esse:
1. ordinanza normale, ovvero, impone le zone;
2. ordinanza di proroga, ovvero, allunga la durata delle restrizioni;
3. sovrapposizione, ovvero, una ordinanza che esce dopo ma che riguarda comuni e date precedenti (vedi ord.38 per tutta la provincia di Palermo)
4. ordinanza di revoca, ovvero, fa cessare la vaidità di ordinanze precedenti

https://docs.google.com/spreadsheets/d/1qHGoC3qEkH6jyANNwsIkqnuLZk_gcaV5bSX4COphyYs/edit?usp=sharing

**Comment by dennisangemi** [comment]
Ottimo lavoro @pigreco. Che fine farà il vecchio sheet? Quale verrà aggiornato? Il repo da dove deve importare i dati?

**Comment by gbvitrano** [comment]
finché è possibile si possono mantenere entrambi? soprattutto per la mappa e tabelle di datawrapper devo ricostruire tutti gli sheet che servono, e visto che ho una certa età devo ricordare cosa ho fatto e rifarlo... :-) :-) :-) 
Domanda posso riscostruire gli sheet necessari nello stesso sheet delle nuove ordinanze ho è meglio in un nuovo scheet?

**Comment by pigreco** [comment]
> Ottimo lavoro @pigreco. Che fine farà il vecchio sheet? Quale verrà aggiornato? Il repo da dove deve importare i dati?

grazie :-),
le sorti dei due sheet le decidiamo assieme, secondo me quello nuovo ha caratteristiche migliori.

@gbvitrano decidiamo assieme quale dei due utilizzare per il futuro, per adesso non è troppo faticoso aggiornali entrambi.

**Comment by dennisangemi** [comment]
Ciao @pigreco, ho collegato il repo al nuovo sheet. In questa commit puoi vedere il diff con le correzioni che tu stesso hai apportato https://github.com/opendatasicilia/ordinanze-covid/commit/c280b7698a599dfd835015659cbb071b488af359 . Se pensi che questa issue possa essere chiusa, fai pure ;)

**Comment by dennisangemi** [comment]
Per sbaglio ho chiuso io ...

**Comment by pigreco** [comment]
grazie
