### ISSUE TITLE
Aggiungare colonne dallo sheet google ad update.yml

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/ordinanze-covid#11]
@dennisangemi per favore puoi aggiungere le colonne  `proroga/cessa` `sovrapposizione` `cessa`

**Comment by dennisangemi** [comment]
Certo @gbvitrano , prima però rivedrei i nomi dei campi (Es. rimuovere lo `/`) e la semantica. Aggiungo qualche commento nello sheet

**Comment by dennisangemi** [comment]
@gbvitrano @pigreco non ho mai capito a cosa servono questi campi e a cosa fanno riferimento. Per favore potete definirli? Thx

p.s.
Non chiamerei un campo `proroga_cessa` e l'altro `cessa`. Sembrano la stessa cosa. Ne facciamo uno per proroga e uno per cessa? Scusate se sono approssimativo ma non posso metterci troppo tempo.

**Comment by pigreco** [comment]
per favore, fermateviiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii

**Comment by dennisangemi** [comment]
Sorry @pigreco, mi è stato chiesto di fare una cosa e ho sollevato qualche criticità. Più lentamente facciamo, meglio è (almeno per me)

**Comment by gbvitrano** [comment]
ok resto in attesa :-)

**Comment by gbvitrano** [comment]
nell'attesa ho usato quello che avevo :-) 

Esempio Gela con 8 ordinanze 
7 sono esecutive e 1 di revoca  
oppure si può dire  7 ordinanze applicate ed 1 abrogata 
Appena ci saranno i dati definitivi, rivedo tutto :-) 
![image](https://user-images.githubusercontent.com/20488693/149010334-7c199168-527d-47c0-aca5-a360dee31fb5.png)
![image](https://user-images.githubusercontent.com/20488693/149010485-33b583f3-6df1-47f5-a1fd-fbc0960bc2ff.png)

**Comment by dennisangemi** [comment]
@gbvitrano dato che abbiamo il nuovo sheet possiamo chiudere questa issue?

**Comment by gbvitrano** [comment]
se se
