### ISSUE TITLE
link errato per l'ordinanza...o numero errato per link ordinanza

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/ordinanze-covid#12]
@pigreco l'ordinanza **64** delk 2021 ha il link al file pdf dell'ordinanza 63.
In realtà andrebbe cambiato il numero dell'ordinanza, da 64 a 63
Cmq prima verifica...che è meglio :-)

**Comment by pigreco** [comment]
avevo già coretto, grazie per la segnalazione
entro oggi termino la revisione
