### ISSUE TITLE
'tbd' che significa?

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/ordinanze-covid#3]
Dare un significato al termine 'tbd' nello schema dati nel file README.

Grazie

**Comment by dennisangemi** [comment]
ciao @cirospat attualmente non significa niente. Sarebbe _to be determined_ ma secondo me quei campi non vanno inclusi nel csv pubblicato ;)

**Comment by cirospat** [comment]
Ok
Allora per intellegibilitá per ora scrivilo nel README il significato.
Così che tutti capiscono.
Grazie :)

**Comment by dennisangemi** [comment]
Fatto, Grazie!
