### ISSUE TITLE
Permessi

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ordinanze-covid#5]
Ciao @aborruso, per favore, quando puoi, potresti darmi i permessi per modificare le informazioni di questo repo? La fase del trasferimento della ownership si sarà mangiata le autorizzazioni. Grazie ;)

**Comment by aborruso** [comment]
Guarda adesso, e nel caso chiudi.

**Comment by dennisangemi** [comment]
Grazie mille @aborruso
