### ISSUE TITLE
Data ordinanza errata (forse)

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/ordinanze-covid#8]
@pigreco per favore puoi controllare la data dell'ordinanza che ha messo il Comune di Cerami in zona rossa dal 16 apr 2021 al 28 apr 2021

![2022-01-09_23h49_59](https://user-images.githubusercontent.com/20488693/148711367-14e26766-a9e1-4396-a686-f3aa305d5636.png)

**Comment by pigreco** [comment]
Sistemato,
grazie!

**Comment by dennisangemi** [comment]
385665acbe4c4bfa84980f82521aa14e6a4df038
