### ISSUE TITLE
data inizio e fine coincidenti

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/ordinanze-covid#9]
Ciao @pigreco,
ci sono alcuni record che hanno data inizio e fine coincidenti.
È corretto?

![image](https://user-images.githubusercontent.com/30607/148843729-2f3c8cd3-d135-4ac5-92a5-e8fad067dc79.png)

**Comment by dennisangemi** [comment]
Ciao @aborruso, mi permetto di risponderti perchè avevo già fatto una domanda simile a Totò tramite commento gsheet. In sostanza (se non ho capito male) questo è il modo in cui teniamo traccia delle ordinanze che fanno cessare i provvedimenti in corso. Nel caso da te selezionato, ad esempio, la zona rossa per il comune di Gela è stata interrotta il 13 maggio 2021 nonostante sarebbe dovuta finire dopo.

Spero di non aver sbagliato. Chiedo comunque conferma a @pigreco

**Comment by aborruso** [comment]
> questo è il modo in cui teniamo traccia delle ordinanze che fanno cessare i provvedimenti in corso

Quindi questi casi, non ininfluenti sul calcolo della durata. Corretto?

**Comment by dennisangemi** [comment]
> Quindi questi casi, non ininfluenti sul calcolo della durata. Corretto?

Esatto, credo proprio di sì @aborruso

**Comment by pigreco** [comment]
Buongiorno,
sono casi un po' particolari e che ricordo di aver sollevato il problema ma senza una vera soluzione.
In questo caso specifico ci furono due ordinanze una dietro l'altra in cui la seconda annullava la prima, quindi il modo per annullare Gela era quella di metterci la stessa data.

perché dovrebbero influire sul calcolo della durata?

**Comment by aborruso** [comment]
> perché dovrebbero influire sul calcolo della durata?

Sono bacchettone e chiedo. Grazie

**Comment by gbvitrano** [comment]
Influiscono anche nel calcolo dei giorni e  influiscono sul calcolo delle ordinanze per Comune.
in realtà il numero delle ordinanza che mettono Gela in zona rossa sono 6 e 2 per annullare una precedente ordinanza....

Quindi anche i giorni sono falsati, quanti giorni prima è stata annullata rispetto all'ordinanza che la metteva in zona rossa...?

Esempio per zona rossa: 
10 giorni con l'Ordinanza X
dopo 3 giorni l'Ordinanza Y sospende l'Ordinanza X
Quindi sono 3 giorni in zona rossa e non 10 

Sbaglio???

![image](https://user-images.githubusercontent.com/20488693/148926127-35efba36-953d-4ee7-bb6d-4400e53b415b.png)

**Comment by pigreco** [comment]
Premessa:
per ogni ordinanza ho sempre aggiunto i comuni presenti nell'ordinanza stessa, anche a costo di essere ripetitivi (questa è la tecnica consigliata da @aborruso e utilizzata dalla protezione civile)

> Esempio per zona rossa: 10 giorni con l'Ordinanza X dopo 3 giorni l'Ordinanza Y sospende l'Ordinanza X Quindi sono 3 giorni in zona rossa e non 10
> 
> Sbaglio??

nel tuo esempio:
avrei scritto tutti i comuni dell'ordinanza X e relative date; poi avrei riscritto nuovamente i comuni dell'ordinanza Y che sospende l'ordinanza X, infatti nascono cosi le date uguali in data inizio e data fine

comunque, per sicurezza, soprattutto per non scrivere boiate nel blog post, occorre una revisione totale come proposto nell'issue #10

**Comment by gbvitrano** [comment]
Queste dovrebbero essere le Ordinanze che azzerano le zone (Giorni 0)

![2022-01-11_12h56_30](https://user-images.githubusercontent.com/20488693/148938549-04f3fc42-7689-4f44-9d46-1cc1db881f51.png)

**Comment by pigreco** [comment]
> Queste dovrebbero essere le Ordinanze che azzerano le zone (Giorni 0)
> 
> ![2022-01-11_12h56_30](https://user-images.githubusercontent.com/20488693/148938549-04f3fc42-7689-4f44-9d46-1cc1db881f51.png)

in teoria sì, ma ci sono oltre 100 ordinanze e l'errore è sempre dietro l'angolo

**Comment by gbvitrano** [comment]
Osservazione su Gela, 
l'ordinanza 55 dispone
l'ordinanza 56 revoca 
quindi Gela ha avuto 8 Ordinane 
7 esecutive
1 di revoca

![image](https://user-images.githubusercontent.com/20488693/148987540-0dcf44a4-fc7d-4b6f-a06a-0a959d09de04.png)
